(function(){
'use strict';
const CFG=window.PM_BACKEND||{};
const BASE=String(CFG.url||'').replace(/\/$/,'');
const KEY=CFG.publishableKey||'';
const ADMIN=(CFG.adminEmail||'umutparoglu87@gmail.com').toLowerCase();
const SESSION_KEY='pm_admin_session_v121';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const loginView=$('#loginView'),adminApp=$('#adminApp'),toastEl=$('#toast');
let session=null, activeView='dashboard';
let cache={content:[],projects:[],brands:[],media:[],briefs:[]};

const contentDefs=[
 ['Navigasyon','nav.about','Hakkımda','Hakkımda menüsü'],['Navigasyon','nav.services','Hizmetler','Hizmetler menüsü'],['Navigasyon','nav.work','İşler','İşler menüsü'],['Navigasyon','nav.quote','Teklif Al ↗','Teklif Al butonu'],['Navigasyon','nav.contact','İletişim','İletişim menüsü'],
 ['Ana Sayfa','home.hero_kicker','KREATİF PRODÜKSİYON · FOTOĞRAF · VİDEO · TASARIM','Hero üst yazı'],['Ana Sayfa','home.hero_line1','Görünen değil,','Hero slogan 1'],['Ana Sayfa','home.hero_line2','hatırlanan işler.','Hero slogan 2'],['Ana Sayfa','home.hero_copy','Markaların, etkinliklerin ve projelerin hikâyesini güçlü görsellere dönüştürüyorum. Stratejiden çekime, tasarımdan post prodüksiyona kadar süreci tek bir yaratıcı çizgide yönetiyorum.','Hero açıklama','textarea'],
 ['İşler','works.kicker','PORTFOLYO / 2022—2026','Üst yazı'],['İşler','works.title','İşler','Başlık'],['İşler','works.lead','Farklı disiplinlerde üretilen seçili projeler. Her iş; amacı, platformu ve görsel dili içinde kendi hikâyesiyle sunuluyor.','Açıklama','textarea'],
 ['Hizmetler','services.kicker','NE ÜRETİYORUM?','Üst yazı'],['Hizmetler','services.title','Hizmetler','Başlık'],['Hizmetler','services.lead','Tek bir format satmıyorum. Markanın hedefini, platformu ve kullanım biçimini anlayıp doğru üretim kombinasyonunu kuruyorum.','Açıklama','textarea'],
 ['Hizmetler','service.reels.title','Video Prodüksiyon','Video başlık'],['Hizmetler','service.reels.summary','Reklam filmi, Reels, etkinlik, konser, kurumsal tanıtım, ürün ve mekân videoları.','Video özet','textarea'],['Hizmetler','service.reels.process','Brief → fikir → çekim planı → prodüksiyon → kurgu → revizyon → teslim.','Video süreç','textarea'],['Hizmetler','service.reels.myth','İyi Reels sadece hızlı kurgu değildir. İlk saniye, hikâye ve izleme davranışı birlikte düşünülür.','Video not','textarea'],
 ['Hizmetler','service.photo.title','Fotoğraf','Fotoğraf başlık'],['Hizmetler','service.photo.summary','Spor, etkinlik, ürün, portre ve kurumsal fotoğraf çekimleri.','Fotoğraf özet','textarea'],['Hizmetler','service.photo.process','Fotoğrafı yalnızca çekmek değil, nerede kullanılacağını bilerek kadrajlamak önemli. Kampanya, web, sosyal medya ve baskı için teslimler ayrı hazırlanabilir.','Fotoğraf süreç','textarea'],['Hizmetler','service.photo.myth','Yüksek megapiksel tek başına iyi fotoğraf demek değildir; ışık, lens, kompozisyon ve son işlem sonucu belirler.','Fotoğraf not','textarea'],
 ['Hizmetler','service.design.title','Tasarım','Tasarım başlık'],['Hizmetler','service.design.summary','Kampanya görselleri, sosyal medya, afiş, baskı ve marka iletişimi.','Tasarım özet','textarea'],['Hizmetler','service.design.process','Önce mesaj hiyerarşisi, sonra görsel dil. Tek bir güzel görsel yerine tekrar üretilebilir bir sistem kurmayı hedefliyorum.','Tasarım süreç','textarea'],['Hizmetler','service.design.myth','Tasarım sadece “güzel görünmek” değildir; bilgiyi doğru sırayla okutmak ve markayı hatırlanır kılmaktır.','Tasarım not','textarea'],
 ['Hizmetler','service.social.title','Sosyal Medya','Sosyal medya başlık'],['Hizmetler','service.social.summary','Sayfa yönetimi, içerik planlaması, Reels, tasarım ve çekim süreçlerinin birlikte yönetimi.','Sosyal medya özet','textarea'],['Hizmetler','service.social.process','İçerikler birbirinden bağımsız değil; profilin genel görünümü, yayın sıklığı, içerik çeşitliliği ve marka tonu birlikte düşünülür.','Sosyal medya süreç','textarea'],['Hizmetler','service.social.myth','Sosyal medya yönetimi yalnızca post paylaşmak değildir. Düzenli içerik sistemi ve marka hafızası oluşturmak asıl iştir.','Sosyal medya not','textarea'],
 ['Hizmetler','service.drone.title','Drone','Drone başlık'],['Hizmetler','service.drone.summary','Mimari, etkinlik, spor ve reklam projelerinde sinematik hava çekimleri.','Drone özet','textarea'],['Hizmetler','service.drone.process','Drone görüntüsü sırf havadan çekilmiş olmak için kullanılmaz; hareket, ölçek ve sahnenin ritmi için planlanır.','Drone süreç','textarea'],
 ['Hizmetler','service.digital.title','Web & Dijital','Dijital başlık'],['Hizmetler','service.digital.summary','Portfolyo siteleri, landing page’ler ve yaratıcı web deneyimleri.','Dijital özet','textarea'],['Hizmetler','service.digital.process','Siteyi yalnızca “bilgi veren sayfa” olarak değil, markanın işlerini güçlü gösteren dijital deneyim olarak ele alıyorum.','Dijital süreç','textarea'],
 ['Hakkımda','about.kicker','UMUT PAROĞLU','Üst yazı'],['Hakkımda','about.title','Hakkımda','Başlık'],['Hakkımda','about.headline','Bir işi sadece üretmiyorum; nasıl hatırlanacağını da düşünüyorum.','Ana cümle','textarea'],['Hakkımda','about.p1','24 yaşındayım. Dört yılı aşkın süredir profesyonel olarak reklam ajansı dünyasının içinde video, fotoğraf, grafik tasarım, sosyal medya ve içerik üretimi üzerine çalışıyorum. Bu sürecin öncesinde de amatör olarak görsel üretim yapıyordum.','Paragraf 1','textarea'],['Hakkımda','about.p2','Paroglu Media; Reels kurgusundan çekime, fotoğraftan tasarıma, drone görüntülerinden web deneyimlerine kadar farklı disiplinleri tek bir görsel bakış altında topladığım kişisel kreatif markam. Amacım tek tek “işler” çıkarmaktan çok, markanın nasıl göründüğünü ve nasıl hatırlandığını güçlendirmek.','Paragraf 2','textarea'],['Hakkımda','about.stat1_value','4+','İstatistik 1 değer'],['Hakkımda','about.stat1_label','Yıl profesyonel deneyim','İstatistik 1 açıklama'],['Hakkımda','about.stat2_value','1000+','İstatistik 2 değer'],['Hakkımda','about.stat2_label','Üretilen içerik / kreatif çıktı','İstatistik 2 açıklama'],['Hakkımda','about.stat3_value','360°','İstatistik 3 değer'],['Hakkımda','about.stat3_label','Çok disiplinli kreatif üretim','İstatistik 3 açıklama'],['Hakkımda','about.manifesto_title','Tek bir uzmanlık değil, tek bir bakış açısı.','Manifesto başlık'],['Hakkımda','about.manifesto_text','Bir projede gerektiğinde kamera arkasında, gerektiğinde kurgu masasında, gerektiğinde tasarım ekranında olabilmek; ortaya çıkan işin parçalarının birbirinden kopmamasını sağlıyor.','Manifesto metin','textarea'],
 ['İletişim','contact.email','umutparoglu87@gmail.com','E-posta'],['İletişim','contact.email_href','mailto:umutparoglu87@gmail.com','E-posta linki'],['İletişim','contact.phone','+90 541 662 98 62','Telefon'],['İletişim','contact.phone_href','tel:+905416629862','Telefon linki'],['İletişim','contact.instagram','@iamparoglu ↗','Instagram'],['İletişim','contact.instagram_href','https://www.instagram.com/iamparoglu/','Instagram linki'],['İletişim','contact.linkedin','LinkedIn ↗','LinkedIn'],['İletişim','contact.linkedin_href','https://www.linkedin.com/in/umut-paro%C4%9Flu-27a630281/','LinkedIn linki'],
 ['Footer','footer.cta_start','Bir sonraki işi','CTA başlangıç'],['Footer','footer.cta_link','birlikte yapalım.','CTA link'],['Footer','footer.disciplines','Reels · Fotoğraf · Tasarım · Sosyal Medya · Drone · Dijital','Disiplinler'],
 ['Ayarlar','brands.carousel_limit','16','Ana sayfa marka limiti'],['Ayarlar','brands.speed_seconds','34','Marka akış süresi'],['Ayarlar','motion.intro_home_ms','1200','Açılış animasyonu ms']
].map(x=>({section:x[0],key:x[1],value:x[2],label:x[3],type:x[4]||'text'}));

const defaultProjects=[
 {title:'Karabük İdman Yurdu',client:'Karabük İdman Yurdu',category:'Sosyal Medya',content_type:'Spor',tags:'Maç Günü, Transfer, Taraftar, Tasarım',description:'Spor kulübü sosyal medya ve tasarım çalışmaları.',cover_url:'karabuk-idman-yurdu-01.png',project_url:'karabuk-idman-yurdu.html',year:2026,ratio:'4:5',filter_tags:'social,sport,film,photo,design',sort_order:1,featured:true,published:true},
 {title:'Konser İçerikleri',client:'SEFO · Hakan Peker · Dedublüman · Poizi',category:'Konser',content_type:'Video / Reels',tags:'Sahne, Backstage, Dikey Video',description:'Konser ve sahne odaklı video içerikleri.',cover_url:'concert-sefo-poster.jpg',project_url:'konser.html',year:2026,ratio:'4:5',filter_tags:'concert,film',sort_order:2,featured:true,published:true},
 {title:'Maç Günü Tasarımları',client:'Kepezspor',category:'Sosyal Medya',content_type:'Spor',tags:'Maç Günü, Tasarım, Spor İletişimi',description:'Kepezspor için maç günü ve spor iletişimi tasarımları.',cover_url:'kepezspor-matchday-01.jpg',project_url:'kepezspor.html',year:2026,ratio:'4:5',filter_tags:'social,sport,design',sort_order:3,featured:true,published:true},
 {title:'Çorluspor 1947',client:'Çorluspor 1947',category:'Sosyal Medya',content_type:'Spor',tags:'Maç Günü, İlk 11, Maç Sonucu, Kupa',description:'Çorluspor 1947 sosyal medya tasarım serisi.',cover_url:'corluspor-1947-01.jpg',project_url:'corluspor.html',year:2026,ratio:'4:5',filter_tags:'social,sport,design',sort_order:4,featured:true,published:true},
 {title:'Tasarım Çalışmaları',client:'Seçili marka çalışmaları',category:'Grafik Tasarım',content_type:'Sosyal Medya',tags:'Sosyal Medya, Outdoor, Kampanya, Kurumsal',description:'Seçili grafik tasarım ve kampanya işleri.',cover_url:'design-yilmaz-gucumuz-ekibimiz.jpg',project_url:'tasarim.html',year:2026,ratio:'4:5',filter_tags:'design,social',sort_order:5,featured:false,published:true},
 {title:'Mimari / İnşaat',client:'',category:'Drone',content_type:'Mimari',tags:'Drone, Reels, Fotoğraf',description:'Mimari ve inşaat projeleri için hava ve görsel prodüksiyon.',cover_url:'cover-drone.jpg',project_url:'drone.html',year:2026,ratio:'16:9',filter_tags:'drone,film,photo',sort_order:6,featured:false,published:true}
];
const defaultBrands=['SGB MOTORS','KARABÜK İDMAN YURDU','FITNESS CLUB','KEPEZSPOR','ÇORLUSPOR 1947','SİBELİN SANAT ATÖLYESİ','ACK BIÇAK'].map((name,i)=>({name,row_no:i<3?1:2,sort_order:i+1,visible:true}));

function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function showToast(msg,bad=false){toastEl.textContent=msg;toastEl.style.borderColor=bad?'rgba(255,111,133,.4)':'rgba(101,230,181,.24)';toastEl.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toastEl.classList.remove('show'),2800)}
function setLoading(on){adminApp?.classList.toggle('loading',!!on)}
function storeSession(s){session=s;localStorage.setItem(SESSION_KEY,JSON.stringify(s))}
function clearSession(){session=null;localStorage.removeItem(SESSION_KEY)}
function loadSession(){try{session=JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{session=null}}
async function raw(path,opt={}){const h={apikey:KEY,Accept:'application/json',...(opt.headers||{})};const r=await fetch(BASE+path,{...opt,headers:h});let body=null;const txt=await r.text();if(txt){try{body=JSON.parse(txt)}catch{body=txt}}if(!r.ok){const msg=body?.message||body?.msg||body?.error_description||body?.error||`${r.status} ${r.statusText}`;const e=new Error(msg);e.status=r.status;throw e}return body}
async function refreshSession(){if(!session?.refresh_token)throw new Error('Oturum süresi doldu');const s=await raw('/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})});if(String(s.user?.email||'').toLowerCase()!==ADMIN)throw new Error('Bu kullanıcı yetkili değil');s.expires_at=s.expires_at||Math.floor(Date.now()/1000)+(s.expires_in||3600);storeSession(s);return s}
async function ensureSession(){if(!session)throw new Error('Giriş gerekli');const exp=session.expires_at||0;if(exp-Math.floor(Date.now()/1000)<90)await refreshSession();return session}
async function authHeaders(){await ensureSession();return {apikey:KEY,Authorization:`Bearer ${session.access_token}`,Accept:'application/json'}}
async function db(table,{method='GET',query='',body,prefer}={}){const headers=await authHeaders();if(body!==undefined)headers['Content-Type']='application/json';if(prefer)headers.Prefer=prefer;return raw(`/rest/v1/${table}${query?`?${query}`:''}`,{method,headers,body:body===undefined?undefined:JSON.stringify(body)})}
async function login(email,password){const s=await raw('/auth/v1/token?grant_type=password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(String(s.user?.email||'').toLowerCase()!==ADMIN)throw new Error('Bu hesap admin olarak yetkili değil');s.expires_at=s.expires_at||Math.floor(Date.now()/1000)+(s.expires_in||3600);storeSession(s);return s}

async function seedFreshDatabase(){
 const rows=await db('site_content',{query:'select=key'});const have=new Set((rows||[]).map(x=>x.key));const missing=contentDefs.filter(x=>!have.has(x.key)).map(({key,value,section,label})=>({key,value,section,label}));if(missing.length)await db('site_content',{method:'POST',body:missing,prefer:'resolution=merge-duplicates,return=minimal'});
 const projects=await db('projects',{query:'select=id&limit=1'});if(!projects?.length)await db('projects',{method:'POST',body:defaultProjects,prefer:'return=minimal'});
 const brands=await db('brands',{query:'select=id&limit=1'});if(!brands?.length)await db('brands',{method:'POST',body:defaultBrands,prefer:'return=minimal'});
}

async function loadAll(){
 const [content,projects,brands,media,briefs]=await Promise.all([
  db('site_content',{query:'select=*&order=section.asc,label.asc'}),
  db('projects',{query:'select=*&order=sort_order.asc,created_at.desc'}),
  db('brands',{query:'select=*&order=row_no.asc,sort_order.asc,created_at.asc'}),
  db('media_library',{query:'select=*&order=created_at.desc'}),
  db('briefs',{query:'select=*&order=created_at.desc'})
 ]);
 cache={content:content||[],projects:projects||[],brands:brands||[],media:media||[],briefs:briefs||[]};
}

function dashboard(){
 const fresh=cache.briefs.filter(x=>x.status==='Yeni').length;
 $('#view-dashboard').innerHTML=`<div class="dashboard-grid">
 <article class="stat-card"><small>PORTFOLYO</small><strong>${cache.projects.length}</strong><em>proje</em></article>
 <article class="stat-card"><small>MARKALAR</small><strong>${cache.brands.filter(x=>x.visible).length}</strong><em>aktif referans</em></article>
 <article class="stat-card"><small>MEDYA</small><strong>${cache.media.length}</strong><em>dosya</em></article>
 <article class="stat-card"><small>YENİ TALEP</small><strong>${fresh}</strong><em>brief</em></article></div>
 <div class="panel-card"><div class="panel-head"><div><h3>Sistem durumu</h3><p>GitHub Pages ön yüzü ve Supabase içerik katmanı aynı veriyi kullanıyor.</p></div><span class="badge on">BAĞLI</span></div><div class="brief-meta"><span class="badge">V12 Motion</span><span class="badge">Supabase Auth</span><span class="badge">RLS açık</span><span class="badge">Media Storage</span></div></div>
 <div class="panel-card"><div class="panel-head"><div><h3>Son talepler</h3><p>Web sitesinden gelen en güncel proje briefleri.</p></div><button class="btn" data-jump="briefs">Tümünü gör ↗</button></div>${cache.briefs.slice(0,4).map(b=>`<div class="brief-card"><div class="brief-top"><div><h4>${esc(b.company||b.name||'İsimsiz talep')}</h4><small>${esc(b.service||b.project_type||'Proje')} · ${new Date(b.created_at).toLocaleDateString('tr-TR')}</small></div><span class="badge ${b.status==='Yeni'?'on':''}">${esc(b.status)}</span></div></div>`).join('')||'<div class="empty">Henüz talep yok.</div>'}</div>`;
 $$('[data-jump]').forEach(b=>b.onclick=()=>switchView(b.dataset.jump));
}

function contentView(){
 const map=Object.fromEntries(cache.content.map(x=>[x.key,x.value]));const groups={};contentDefs.forEach(d=>(groups[d.section]??=[]).push(d));
 $('#view-content').innerHTML=`<div class="toolbar"><div class="left"><span class="section-kicker">CANLI İÇERİK</span></div><div class="right"><button class="btn-primary" id="saveAllContent">Tüm Değişiklikleri Kaydet</button></div></div><div class="content-groups">${Object.entries(groups).map(([section,items])=>`<div class="content-section"><h3>${esc(section)}</h3><div class="content-fields">${items.map(d=>`<label class="field ${d.type==='textarea'?'wide':''}"><span>${esc(d.label)}</span>${d.type==='textarea'?`<textarea data-content-key="${esc(d.key)}">${esc(map[d.key]??d.value)}</textarea>`:`<input data-content-key="${esc(d.key)}" value="${esc(map[d.key]??d.value)}">`}<small>${esc(d.key)}</small></label>`).join('')}</div></div>`).join('')}</div>`;
 $('#saveAllContent').onclick=saveAllContent;
}
async function saveAllContent(){try{setLoading(true);const rows=$$('[data-content-key]').map(el=>{const d=contentDefs.find(x=>x.key===el.dataset.contentKey);return {key:el.dataset.contentKey,value:el.value,section:d?.section||'Genel',label:d?.label||el.dataset.contentKey}});await db('site_content',{method:'POST',query:'on_conflict=key',body:rows,prefer:'resolution=merge-duplicates,return=representation'});cache.content=await db('site_content',{query:'select=*&order=section.asc,label.asc'});showToast('Site içerikleri kaydedildi ✓')}catch(e){showToast(e.message,true)}finally{setLoading(false)}}

function projectsView(){
 $('#view-projects').innerHTML=`<div class="toolbar"><div class="left"><input class="search" id="projectSearch" placeholder="Projelerde ara..."></div><div class="right"><button class="btn-primary" id="newProject">+ Yeni Proje</button></div></div><div id="projectTable"></div>`;
 $('#newProject').onclick=()=>openProject();$('#projectSearch').oninput=renderProjectTable;renderProjectTable();
}
function renderProjectTable(){const q=($('#projectSearch')?.value||'').toLocaleLowerCase('tr-TR');const rows=cache.projects.filter(p=>[p.title,p.client,p.category].join(' ').toLocaleLowerCase('tr-TR').includes(q));$('#projectTable').innerHTML=rows.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>PROJE</th><th>KATEGORİ</th><th>YIL</th><th>ÖNE ÇIKAN</th><th>YAYIN</th><th></th></tr></thead><tbody>${rows.map(p=>`<tr><td><div class="row-title">${p.cover_url?`<img class="thumb" src="${esc(p.cover_url)}" onerror="this.style.visibility='hidden'">`:''}<div><strong>${esc(p.title)}</strong><br><small>${esc(p.client||'')}</small></div></div></td><td>${esc([p.category,p.content_type].filter(Boolean).join(' · '))}</td><td>${esc(p.year||'')}</td><td><span class="badge ${p.featured?'on':''}">${p.featured?'Evet':'Hayır'}</span></td><td><span class="badge ${p.published?'on':''}">${p.published?'Yayında':'Taslak'}</span></td><td><div class="actions"><button class="btn" data-edit-project="${p.id}">Düzenle</button><button class="btn-danger" data-del-project="${p.id}">Sil</button></div></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Proje bulunamadı.</div>';$$('[data-edit-project]').forEach(b=>b.onclick=()=>openProject(cache.projects.find(x=>x.id===b.dataset.editProject)));$$('[data-del-project]').forEach(b=>b.onclick=()=>deleteRecord('projects',b.dataset.delProject,'Bu projeyi silmek istediğine emin misin?',loadProjects));}
async function loadProjects(){cache.projects=await db('projects',{query:'select=*&order=sort_order.asc,created_at.desc'});renderProjectTable();dashboard()}
function openProject(p={}){openEditor(p.id?'PROJEYİ DÜZENLE':'YENİ PROJE',p.title||'Proje',[
 ['title','Proje adı',p.title||'',true],['client','Müşteri / marka',p.client||''],['category','Kategori',p.category||''],['content_type','İçerik türü',p.content_type||''],['tags','Etiketler (virgülle)',p.tags||'','wide'],['filter_tags','Filtreler: sport,design... ',p.filter_tags||'','wide'],['year','Yıl',p.year||2026,'number'],['ratio','Oran',p.ratio||'4:5'],['cover_url','Kapak görseli URL / dosya adı',p.cover_url||'','wide'],['media_url','İkinci medya / video URL',p.media_url||'','wide'],['media_type','İkinci medya türü',p.media_type||'image','select',['image','video']],['project_url','Proje sayfası',p.project_url||'','wide'],['sort_order','Sıra',p.sort_order??0,'number'],['description','Açıklama',p.description||'','textarea'],['featured','Ana sayfada öne çıkar',!!p.featured,'check'],['published','Yayında',p.published!==false,'check']],async data=>{if(p.id)await db('projects',{method:'PATCH',query:`id=eq.${encodeURIComponent(p.id)}`,body:data,prefer:'return=representation'});else await db('projects',{method:'POST',body:data,prefer:'return=representation'});await loadProjects();showToast('Proje kaydedildi ✓')})}

function brandsView(){
 $('#view-brands').innerHTML=`<div class="toolbar"><div class="left"><input class="search" id="brandSearch" placeholder="Markalarda ara..."></div><div class="right"><button class="btn-primary" id="newBrand">+ Yeni Marka</button></div></div><div id="brandTable"></div>`;$('#newBrand').onclick=()=>openBrand();$('#brandSearch').oninput=renderBrandTable;renderBrandTable();
}
function renderBrandTable(){const q=($('#brandSearch')?.value||'').toLocaleLowerCase('tr-TR');const rows=cache.brands.filter(b=>String(b.name).toLocaleLowerCase('tr-TR').includes(q));$('#brandTable').innerHTML=rows.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>MARKA</th><th>SATIR</th><th>SIRA</th><th>GÖRÜNÜR</th><th></th></tr></thead><tbody>${rows.map(b=>`<tr><td><div class="row-title">${b.logo_url?`<img class="thumb" src="${esc(b.logo_url)}">`:''}<strong>${esc(b.name)}</strong></div></td><td>${esc(b.row_no||1)}</td><td>${esc(b.sort_order||0)}</td><td><span class="badge ${b.visible?'on':''}">${b.visible?'Evet':'Hayır'}</span></td><td><div class="actions"><button class="btn" data-edit-brand="${b.id}">Düzenle</button><button class="btn-danger" data-del-brand="${b.id}">Sil</button></div></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Marka bulunamadı.</div>';$$('[data-edit-brand]').forEach(x=>x.onclick=()=>openBrand(cache.brands.find(b=>b.id===x.dataset.editBrand)));$$('[data-del-brand]').forEach(x=>x.onclick=()=>deleteRecord('brands',x.dataset.delBrand,'Bu markayı silmek istediğine emin misin?',loadBrands))}
async function loadBrands(){cache.brands=await db('brands',{query:'select=*&order=row_no.asc,sort_order.asc,created_at.asc'});renderBrandTable();dashboard()}
function openBrand(b={}){openEditor(b.id?'MARKAYI DÜZENLE':'YENİ MARKA',b.name||'Marka',[['name','Marka adı',b.name||'',true],['sector','Sektör',b.sector||''],['url','Web / sosyal linki',b.url||'','wide'],['logo_url','Logo URL',b.logo_url||'','wide'],['row_no','Marquee satırı',b.row_no||1,'number'],['sort_order','Sıra',b.sort_order||0,'number'],['visible','Görünür',b.visible!==false,'check']],async data=>{if(b.id)await db('brands',{method:'PATCH',query:`id=eq.${encodeURIComponent(b.id)}`,body:data,prefer:'return=representation'});else await db('brands',{method:'POST',body:data,prefer:'return=representation'});await loadBrands();showToast('Marka kaydedildi ✓')})}

function mediaView(){
 $('#view-media').innerHTML=`<div class="upload-box"><div><strong>Yeni medya yükle</strong><div><small>Görsel, logo veya video — Supabase Storage / media.</small></div></div><input id="mediaFile" type="file" accept="image/*,video/*"><button class="btn-primary" id="uploadMedia">Yükle</button></div><div class="media-grid" id="mediaGrid"></div>`;$('#uploadMedia').onclick=uploadMedia;renderMediaGrid();
}
function renderMediaGrid(){const host=$('#mediaGrid');host.innerHTML=cache.media.length?cache.media.map(m=>`<article class="media-card"><div class="media-preview">${m.media_type==='video'?`<video src="${esc(m.file_url)}" muted controls preload="metadata"></video>`:`<img src="${esc(m.file_url)}" alt="${esc(m.alt_text||m.title||'')}">`}</div><div class="media-card-body"><strong>${esc(m.title||m.file_name||'Medya')}</strong><small>${esc(m.ratio||'original')} · ${m.file_size?Math.round(m.file_size/1024)+' KB':''}</small><div class="actions"><button class="btn" data-copy-media="${esc(m.file_url)}">URL Kopyala</button><button class="btn-danger" data-del-media="${m.id}">Sil</button></div></div></article>`).join(''):'<div class="empty">Henüz medya yüklenmedi.</div>';$$('[data-copy-media]').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(b.dataset.copyMedia);showToast('URL kopyalandı')});$$('[data-del-media]').forEach(b=>b.onclick=()=>deleteMedia(cache.media.find(x=>x.id===b.dataset.delMedia)))}
function safeName(n){return String(n||'file').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'').toLowerCase()||'file'}
async function uploadMedia(){const input=$('#mediaFile'),file=input.files?.[0];if(!file)return showToast('Önce bir dosya seç',true);try{setLoading(true);const headers=await authHeaders();const path=`uploads/${Date.now()}-${safeName(file.name)}`;headers['Content-Type']=file.type||'application/octet-stream';headers['x-upsert']='false';await raw(`/storage/v1/object/media/${path.split('/').map(encodeURIComponent).join('/')}`,{method:'POST',headers,body:file});const url=`${BASE}/storage/v1/object/public/media/${path.split('/').map(encodeURIComponent).join('/')}`;const row={title:file.name.replace(/\.[^.]+$/,''),file_url:url,storage_path:path,media_type:file.type.startsWith('video/')?'video':'image',ratio:'original',alt_text:'',file_name:file.name,file_size:file.size};await db('media_library',{method:'POST',body:row,prefer:'return=representation'});cache.media=await db('media_library',{query:'select=*&order=created_at.desc'});mediaView();showToast('Medya yüklendi ✓')}catch(e){showToast(e.message,true)}finally{setLoading(false)}}
async function deleteMedia(m){if(!m||!confirm('Bu medya dosyası Storage’dan da silinsin mi?'))return;try{setLoading(true);const headers=await authHeaders();try{await raw(`/storage/v1/object/media/${String(m.storage_path).split('/').map(encodeURIComponent).join('/')}`,{method:'DELETE',headers})}catch(e){console.warn(e)}await db('media_library',{method:'DELETE',query:`id=eq.${encodeURIComponent(m.id)}`});cache.media=cache.media.filter(x=>x.id!==m.id);mediaView();showToast('Medya silindi')}catch(e){showToast(e.message,true)}finally{setLoading(false)}}

function briefsView(){
 $('#view-briefs').innerHTML=`<div class="toolbar"><div class="left"><span class="section-kicker">WEB SİTESİ TALEPLERİ</span></div><div class="right"><button class="btn" id="refreshBriefs">Yenile</button></div></div><div id="briefList"></div>`;$('#refreshBriefs').onclick=loadBriefs;renderBriefs();
}
function renderBriefs(){const host=$('#briefList');host.innerHTML=cache.briefs.length?cache.briefs.map(b=>`<article class="brief-card"><div class="brief-top"><div><h4>${esc(b.company||b.name||'İsimsiz talep')}</h4><small>${new Date(b.created_at).toLocaleString('tr-TR')} · ${esc(b.email||b.phone||'İletişim yok')}</small></div><select class="brief-status" data-brief-status="${b.id}">${['Yeni','İletişime Geçildi','Teklif Verildi','Tamamlandı','Arşiv'].map(s=>`<option ${b.status===s?'selected':''}>${s}</option>`).join('')}</select></div><div class="brief-meta"><span class="badge">${esc(b.service||'Hizmet yok')}</span><span class="badge">${esc(b.project_type||'Proje türü yok')}</span><span class="badge">${esc(b.budget||'Bütçe yok')}</span><span class="badge">${esc(b.deadline||'Tarih yok')}</span><span class="badge">${esc(b.city||'Şehir yok')}</span></div>${b.notes?`<p>${esc(b.notes)}</p>`:''}<div class="actions"><a class="btn" href="mailto:${esc(b.email||'')}" style="text-decoration:none">E-posta</a><button class="btn-danger" data-del-brief="${b.id}">Sil</button></div></article>`).join(''):'<div class="empty">Henüz proje talebi yok.</div>';$$('[data-brief-status]').forEach(s=>s.onchange=()=>updateBriefStatus(s.dataset.briefStatus,s.value));$$('[data-del-brief]').forEach(b=>b.onclick=()=>deleteRecord('briefs',b.dataset.delBrief,'Bu talebi silmek istediğine emin misin?',loadBriefs))}
async function loadBriefs(){cache.briefs=await db('briefs',{query:'select=*&order=created_at.desc'});renderBriefs();dashboard()}
async function updateBriefStatus(id,status){try{await db('briefs',{method:'PATCH',query:`id=eq.${encodeURIComponent(id)}`,body:{status},prefer:'return=representation'});const b=cache.briefs.find(x=>x.id===id);if(b)b.status=status;showToast('Durum güncellendi')}catch(e){showToast(e.message,true)}}

async function deleteRecord(table,id,msg,after){if(!confirm(msg))return;try{setLoading(true);await db(table,{method:'DELETE',query:`id=eq.${encodeURIComponent(id)}`});await after();showToast('Silindi')}catch(e){showToast(e.message,true)}finally{setLoading(false)}}

const dialog=$('#editorDialog'),form=$('#editorForm');$('#dialogClose').onclick=()=>dialog.close();
function openEditor(kicker,title,fields,onSave){$('#dialogKicker').textContent=kicker;$('#dialogTitle').textContent=title;form.innerHTML=fields.map(f=>fieldHtml(f)).join('')+`<div class="editor-actions"><button class="btn" type="button" id="cancelEditor">Vazgeç</button><button class="btn-primary" type="submit">Kaydet</button></div>`;$('#cancelEditor').onclick=()=>dialog.close();form.onsubmit=async e=>{e.preventDefault();const data={};fields.forEach(f=>{const [name,,,,type]=f;const el=form.elements[name];if(!el)return;if(type==='check'||f[3]==='check')data[name]=el.checked;else if(type==='number'||f[3]==='number')data[name]=el.value===''?null:Number(el.value);else data[name]=el.value.trim()});try{setLoading(true);await onSave(data);dialog.close()}catch(err){showToast(err.message,true)}finally{setLoading(false)}};dialog.showModal()}
function fieldHtml(f){const [name,label,value,kind,options]=f;const wide=kind==='wide'||kind==='textarea';if(kind==='check')return `<label class="check-row wide"><input name="${name}" type="checkbox" ${value?'checked':''}><span>${esc(label)}</span></label>`;if(kind==='textarea')return `<label class="field wide"><span>${esc(label)}</span><textarea name="${name}">${esc(value)}</textarea></label>`;if(kind==='select')return `<label class="field"><span>${esc(label)}</span><select name="${name}">${(options||[]).map(o=>`<option ${String(o)===String(value)?'selected':''}>${esc(o)}</option>`).join('')}</select></label>`;return `<label class="field ${wide?'wide':''}"><span>${esc(label)}</span><input name="${name}" type="${kind==='number'?'number':'text'}" value="${esc(value)}" ${f[3]===true?'required':''}></label>`}

const titles={dashboard:'Genel Bakış',content:'Site İçerikleri',projects:'Portfolyo',brands:'Markalar',media:'Medya',briefs:'Talepler'};
function switchView(v){activeView=v;$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${v}`));$('#viewTitle').textContent=titles[v]||v;adminApp.classList.remove('nav-open');({dashboard,content:contentView,projects:projectsView,brands:brandsView,media:mediaView,briefs:briefsView}[v]||dashboard)()}
$$('.nav-item').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#mobileNavToggle').onclick=()=>adminApp.classList.toggle('nav-open');
$('#logoutBtn').onclick=async()=>{try{if(session?.access_token){const h=await authHeaders();await raw('/auth/v1/logout',{method:'POST',headers:h})}}catch{}clearSession();location.replace('admin.html')};
$('#loginForm').onsubmit=async e=>{e.preventDefault();const msg=$('#loginMessage');msg.textContent='';try{const btn=e.submitter;btn.disabled=true;btn.textContent='Giriş yapılıyor…';await login($('#loginEmail').value.trim(),$('#loginPassword').value);await startAdmin()}catch(err){msg.textContent=err.message;e.submitter.disabled=false;e.submitter.textContent='Giriş Yap ↗'}};

async function startAdmin(){if(!BASE||!KEY)throw new Error('Supabase bağlantı bilgileri eksik');loginView.hidden=true;adminApp.hidden=false;setLoading(true);try{await seedFreshDatabase();await loadAll();dashboard();switchView('dashboard');showToast('Admin paneli hazır ✓')}finally{setLoading(false)}}

(async function boot(){loadSession();if(session){try{await ensureSession();if(String(session.user?.email||'').toLowerCase()!==ADMIN)throw new Error('Yetkisiz');await startAdmin();return}catch{clearSession()}}location.replace('admin.html')})();
})();
